config/routes.rb
Rails.application.routes.draw do
  
  resources :tests do
    resources :events
  end
  resources :customers
  resources :scenarios
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer
  include Mongoid::Document
  field :customer_name, type: String
end

app/models/event.rb
class Event
  include Mongoid::Document
  field :event_name, type: String
  field :event_date, type: Date
  field :event_outcome, type: String
  embedded_in :test, inverse_of: :events
end

app/models/scenario.rb
class Scenario
  include Mongoid::Document

  field :scenario_name, type: String
  field :scenario_description, type: String
end

app/models/test.rb
class Test
  include Mongoid::Document
  field :test_customer, type: String
  field :test_scenario, type: String
  field :test_start_date, type: Date
  embeds_many :events
  accepts_nested_attributes_for :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  
  def index
    @customers= Customer.all
  end
  
  def new
    @customer = Customer.new
  end
  
  def edit
  end
  
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to customers_path, notice: 'Customer was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end
  
  # POST /customers
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customers_path, notice: 'Customer was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end
  
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_path, notice: 'Customer was successfully deleted.' }
    end
  end
  
    private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end
  
   # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:customer_name)
    end
    
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  
  def index
    @events = Event.all
  end

  def new
    @test = Test.find(params[:test_id])
    @event = Event.new
    @event.build_test
  end

  def edit
  end

  def update
    respond_to do |format|
      if @test.events.update(event_params)
        format.html { redirect_to test_path(@test), notice: 'Event was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def create
    @test = Test.find(params[:test_id])
    @test.events << Event.new(event_params)

    respond_to do |format|
      if @test.save
        format.html { redirect_to test_path(@test), notice: 'Event was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @test.events.destroy
    respond_to do |format|
      format.html { redirect_to test_path(@test), notice: 'Event was successfully deleted.' }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @test = Test.find(params[:test_id])
      @event = @test.events.find(params[:id])
    end
  
   # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:event_name, :event_date, :event_outcome)
    end
    
end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController
  before_action :set_scenario, only: [:show, :edit, :update, :destroy]
  
  def index
    @scenarios = Scenario.all
  end

  def new
    @scenario = Scenario.new
  end

  def edit
  end

  def update
    respond_to do |format|
      if @scenario.update(scenario_params)
        format.html { redirect_to scenarios_path, notice: 'Scenario was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def create
    @scenario = Scenario.new(scenario_params)

    respond_to do |format|
      if @scenario.save
        format.html { redirect_to scenarios_path, notice: 'Scenario was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @scenario.destroy
    respond_to do |format|
      format.html { redirect_to scenarios_path, notice: 'Scenario was successfully deleted.' }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scenario
      @scenario = Scenario.find(params[:id])
    end
  
   # Never trust parameters from the scary internet, only allow the white list through.
    def scenario_params
      params.require(:scenario).permit(:scenario_name, :scenario_description)
    end
  
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :set_test, only: [:show, :edit, :update, :destroy]
  
  def index
    @tests = Test.all.order(test_customer: :asc, test_scenario: :asc)
  end
  
  def show
  end

  def new
    @test = Test.new
    @customers = Customer.distinct(:customer_name)
    @scenarios = Scenario.distinct(:scenario_name)
  end

  def edit
  end

  def update
    respond_to do |format|
      if @test.update(test_params)
        format.html { redirect_to tests_path, notice: 'Test was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def create
    @test = Test.new(test_params)

    respond_to do |format|
      if @test.save
        format.html { redirect_to tests_path, notice: 'Test was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @test.destroy
    respond_to do |format|
      format.html { redirect_to tests_path, notice: 'Test was successfully deleted.' }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test
      @test = Test.find(params[:id])
    end
  
   # Never trust parameters from the scary internet, only allow the white list through.
    def test_params
      params.require(:test).permit(:test_customer, :test_scenario, :test_start_date,
                                  event_attributes: [:event_name, :event_date, :event_outcome])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/customers/_form.html.erb
<%= simple_form_for @customer do |c| %>
            <%= c.input :customer_name, label: 'Customer name' %>
            <%= c.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/customers/edit.html.erb
<div class="container">
    <div class="row">
        <div class="column">
            <h3>Edit customer</h3>
        </div>
    </div>
    

    <div class="row ">
      <div class="col-md-12">
        <%= render 'form', customer: @customer %>
      </div>
    </div>
</div>

app/views/customers/index.html.erb
<div class="container">
    <div class="row">
        <div class="column">
            <h3>Manage customers</h3>
        </div>
    </div>
    

    <div class="row">
        <div class="column">
            <ul>
            <% @customers.each do |c| %>
                <li><%= c.customer_name %> : <%= link_to 'edit', edit_customer_path(c) %> | 
                <%= link_to 'delete', customer_path(c), data: { confirm: 'Are you sure?' }, method: :delete %></li>
            <% end %>
            </ul>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="column">
            <%= button_to "Add customer", new_customer_path, method: :get, class: "btn btn-primary" %>
        </div>
    </div>
</div>

app/views/customers/new.html.erb
<div class="container">
    <div class="row">
        <div class="column">
            <h3>Add customer</h3>
        </div>
    </div>
    

    <div class="row ">
      <div class="col-md-12">
        <%= render 'form', customer: @customer %>
      </div>
    </div>
</div>

app/views/events/_form.html.erb
<%= simple_form_for ([@test, @event ]) do |e| %>
    <%= e.input :event_date, as: :date, html5: true, label: 'System start date' %>
    <%= e.input :event_name, label: 'Event' %>
    <%= e.input :event_outcome, label: 'Outcome' %>
    <%= e.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/events/edit.html.erb
<div class="container">
    <div class="row">
        <div class="column">
            <h3>Edit event</h3>
        </div>
    </div>
    

    <div class="row ">
      <div class="col-md-12">
        <%= render 'form' %>
      </div>
    </div>
</div>

app/views/events/index.html.erb
<div class="container">
    <div class="row">
        <div class="column">
            <h3>Manage events</h3>
        </div>
    </div>
    

    <div class="row">
        <div class="column">
            <ul>
            <% @events.each do |e| %>
                <li><%= e.event_name %> : <%= link_to 'edit', edit_event_path(e) %> | 
                <%= link_to 'delete', event_path(e), data: { confirm: 'Are you sure?' }, method: :delete %></li>
            <% end %>
            </ul>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="column">
            <%= button_to "Add event", new_event_path, method: :get, class: "btn btn-primary" %>
        </div>
    </div>
</div>

app/views/events/new.html.erb
<div class="container">
    <div class="row">
        <div class="column">
            <h3>Add event</h3>
        </div>
    </div>
    

    <div class="row ">
      <div class="col-md-12">
        <%= render 'form' %>
      </div>
    </div>
</div>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">MTime</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor03">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/customers">Customers <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/scenarios">Scenarios</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/tests">Tests</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mtime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render "layouts/menu" %>
    <div class="container">
      <p id="notice"><%= notice %></p>
      <h3><%= yield(:page_title) %></h3>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<% content_for :page_title, 'Time Travel Testing' %>
<p></p>
<%= link_to "Manage customers", customers_path %>
<p></p>
<%= link_to "Manage scenarios", scenarios_path %>
<p></p>
<%= link_to "Manage tests", tests_path %>
<p></p>

app/views/scenarios/_form.html.erb
<%= simple_form_for @scenario do |s| %>
            <%= s.input :scenario_name, label: 'Scenario name' %>
            <%= s.input :scenario_description, as: :text, label: 'Scenario description' %>
            <%= s.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/scenarios/edit.html.erb
<div class="container">
    <div class="row">
        <div class="column">
            <h3>Edit scenario</h3>
        </div>
    </div>
    

    <div class="row ">
      <div class="col-md-12">
        <%= render 'form', scenario: @scenario %>
      </div>
    </div>
</div>

app/views/scenarios/index.html.erb
<div class="container">
    <div class="row">
        <div class="column">
            <h3>Manage scenarios</h3>
        </div>
    </div>
    

    <div class="row">
        <div class="column">
            <ul>
            <% @scenarios.each do |s| %>
                <li><%= s.scenario_name %> : <%= link_to 'edit', edit_scenario_path(s) %> | 
                <%= link_to 'delete', scenario_path(s), data: { confirm: 'Are you sure?' }, method: :delete %></li>
            <% end %>
            </ul>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="column">
            <%= button_to "Add scenario", new_scenario_path, method: :get, class: "btn btn-primary" %>
        </div>
    </div>
</div>

app/views/scenarios/new.html.erb
<div class="container">
    <div class="row">
        <div class="column">
            <h3>Add scenario</h3>
        </div>
    </div>
    

    <div class="row ">
      <div class="col-md-12">
        <%= render 'form', scenario: @scenario %>
      </div>
    </div>
</div>